// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABhEEVkS57i2h9OqZU62NddbcvkbkyuzQ',
    appId: '1:989584554813:web:e6e48d8852a3c59e85a354',
    messagingSenderId: '989584554813',
    projectId: 'coachtrack25',
    authDomain: 'coachtrack25.firebaseapp.com',
    storageBucket: 'coachtrack25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOm2_K5nbtKCaU8yNLz1uMY41DDknS19o',
    appId: '1:989584554813:android:d8eef5c3c83f90ef85a354',
    messagingSenderId: '989584554813',
    projectId: 'naturafit25',
    storageBucket: 'naturafit25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT3IBnOsJgW-5bKu0CJTCiM5yitqZMkWE',
    appId: '1:107791512494:ios:ac18e5c95f67d294408e3f',
    messagingSenderId: '107791512494',
    projectId: 'naturafit25',
    storageBucket: 'naturafit25.firebasestorage.app',
    iosBundleId: 'com.elephantmind.naturafit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT3IBnOsJgW-5bKu0CJTCiM5yitqZMkWE',
    appId: '1:107791512494:ios:ac18e5c95f67d294408e3f',
    messagingSenderId: '107791512494',
    projectId: 'naturafit25',
    storageBucket: 'naturafit25.firebasestorage.app',
    iosBundleId: 'com.elephantmind.naturafit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABhEEVkS57i2h9OqZU62NddbcvkbkyuzQ',
    appId: '1:989584554813:web:0a6c49cf1593533985a354',
    messagingSenderId: '989584554813',
    projectId: 'naturafit25',
    authDomain: 'naturafit25.firebaseapp.com',
    storageBucket: 'naturafit25.firebasestorage.app',
  );
}
