import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:naturafit/services/user_provider.dart';



// SPECIFIC CATEGORIES
/*
final specializationCategories = {
      'All': 'All',
      'Meat & Fish': 'Meat & Fish',
      'Plant-Based Protein': 'Plant-Based Protein',
      'Carbs': 'Carbs',
      'Healthy Fats': 'Healthy Fats',
      'Nuts & Seeds': 'Nuts & Seeds',
      'Fruits': 'Fruits',
      'Vegetables & Greens': 'Vegetables & Greens',
      'Dairy & Alternatives': 'Dairy & Alternatives',
      'Spices & Herbs': 'Spices & Herbs',
      'Condiments': 'Condiments',
    };
    */






class Ingredient {
  final String name;
  final String category; // e.g., 'Protein', 'Carbs', 'Vegetables', etc.
  final double calories;
  final double protein;
  final double carbs;
  final double fats;
  final String servingSize;
  final String servingUnit;
  final List<String> specificCategories;
  const Ingredient({
    required this.name,
    required this.category,
    required this.calories,
    required this.protein,
    required this.carbs,
    required this.fats,
    required this.servingSize,
    required this.servingUnit,
    required this.specificCategories,
  });

  // Helper method to calculate nutrients based on quantity
  Map<String, double> calculateNutrients(double quantity) {
    final multiplier = quantity / double.parse(servingSize);
    return {
      'calories': calories * multiplier,
      'protein': protein * multiplier,
      'carbs': carbs * multiplier,
      'fats': fats * multiplier,
    };
  }

  

  

}

class IngredientsData {
  static List<Ingredient> getIngredients(BuildContext context) {

    final userData = Provider.of<UserProvider>(context, listen: false).userData;
    final weightUnit = userData?['weightUnit'] ?? 'kg';

    return [
      Ingredient(
        name: 'Chicken Breast',
        category: 'Protein',
        calories: 165,
        protein: 31,
        carbs: 0,
        fats: 3.6,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Meat & Fish'],
      ),
      Ingredient(
        name: 'Salmon',
        category: 'Protein',
        calories: 208,
        protein: 22,
        carbs: 0,
        fats: 13,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Meat & Fish', 'Healthy Fats'],
      ),
      const Ingredient(
        name: 'Egg',
        category: 'Protein',
        calories: 72,
        protein: 6.3,
        carbs: 0.4,
        fats: 4.8,
        servingSize: '1',
        servingUnit: 'pc',
        specificCategories: ['Animal Protein'],
      ),
      Ingredient(
        name: 'Brown Rice',
        category: 'Carbs',
        calories: 111,
        protein: 2.6,
        carbs: 23,
        fats: 0.9,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Carbs', 'Plant-Based Protein'],
      ),
      Ingredient(
        name: 'Sweet Potato',
        category: 'Carbs',
        calories: 86,
        protein: 1.6,
        carbs: 20,
        fats: 0.1,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Carbs'],
      ),
      Ingredient(
        name: 'Quinoa',
        category: 'Carbs',
        calories: 120,
        protein: 4.4,
        carbs: 21.3,
        fats: 1.9,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Carbs', 'Plant-Based Protein'],
      ),
      Ingredient(
        name: 'Broccoli',
        category: 'Vegetables',
        calories: 55,
        protein: 3.7,
        carbs: 11.2,
        fats: 0.6,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Vegetables & Greens'],
      ),
      Ingredient(
        name: 'Spinach',
        category: 'Vegetables',
        calories: 23,
        protein: 2.9,
        carbs: 3.6,
        fats: 0.4,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Vegetables & Greens'],
      ),
      const Ingredient(
        name: 'Apple',
        category: 'Fruits',
        calories: 52,
        protein: 0.3,
        carbs: 14,
        fats: 0.2,
        servingSize: '1',
        servingUnit: 'pc',
        specificCategories: ['Fruits'],
      ),
      const Ingredient(
        name: 'Banana',
        category: 'Fruits',
        calories: 89,
        protein: 1.1,
        carbs: 23,
        fats: 0.3,
        servingSize: '1',
        servingUnit: 'pc',
        specificCategories: ['Fruits'],
      ),
      Ingredient(
        name: 'Greek Yogurt',
        category: 'Dairy',
        calories: 59,
        protein: 10,
        carbs: 3.6,
        fats: 0.4,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Dairy & Alternatives'],
      ),
      const Ingredient(
        name: 'Olive Oil',
        category: 'Fats',
        calories: 884,
        protein: 0,
        carbs: 0,
        fats: 100,
        servingSize: '100',
        servingUnit: 'ml',
        specificCategories: ['Healthy Fats', 'Condiments'],
      ),
      const Ingredient(
        name: 'Avocado',
        category: 'Fats',
        calories: 160,
        protein: 2,
        carbs: 8.5,
        fats: 14.7,
        servingSize: '1',
        servingUnit: 'pc',
        specificCategories: ['Healthy Fats', 'Fruits'],
      ),
      // Additional Proteins
      Ingredient(
        name: 'Turkey Breast',
        category: 'Protein',
        calories: 157,
        protein: 29,
        carbs: 0,
        fats: 3.6,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Meat & Fish'],
      ),
      Ingredient(
        name: 'Tofu',
        category: 'Protein',
        calories: 144,
        protein: 15.9,
        carbs: 3.3,
        fats: 8.7,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Plant-Based Protein'],
      ),
      Ingredient(
        name: 'Lentils',
        category: 'Protein',
        calories: 116,
        protein: 9,
        carbs: 20,
        fats: 0.4,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Plant-Based Protein'],
      ),

      // Additional Carbs
      Ingredient(
        name: 'Oats',
        category: 'Carbs',
        calories: 389,
        protein: 16.9,
        carbs: 66.3,
        fats: 6.9,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Carbs', 'Plant-Based Protein'],
      ),
      Ingredient(
        name: 'Whole Wheat Bread',
        category: 'Carbs',
        calories: 247,
        protein: 13,
        carbs: 41,
        fats: 3.4,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Carbs'],
      ),

      // Additional Vegetables
      Ingredient(
        name: 'Kale',
        category: 'Vegetables',
        calories: 49,
        protein: 4.3,
        carbs: 8.8,
        fats: 0.9,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Vegetables & Greens'],
      ),
      Ingredient(
        name: 'Bell Pepper',
        category: 'Vegetables',
        calories: 31,
        protein: 1,
        carbs: 6,
        fats: 0.3,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Vegetables & Greens'],
      ),

      // Additional Fruits
      const Ingredient(
        name: 'Orange',
        category: 'Fruits',
        calories: 47,
        protein: 0.9,
        carbs: 12,
        fats: 0.1,
        servingSize: '1',
        servingUnit: 'pc',
        specificCategories: ['Fruits'],
      ),
      const Ingredient(
        name: 'Blueberries',
        category: 'Fruits',
        calories: 57,
        protein: 0.7,
        carbs: 14,
        fats: 0.3,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Fruits'],
      ),

      // Additional Healthy Fats
      const Ingredient(
        name: 'Almonds',
        category: 'Fats',
        calories: 579,
        protein: 21,
        carbs: 22,
        fats: 49,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Healthy Fats', 'Nuts & Seeds'],
      ),
      const Ingredient(
        name: 'Chia Seeds',
        category: 'Fats',
        calories: 486,
        protein: 17,
        carbs: 42,
        fats: 31,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Healthy Fats', 'Nuts & Seeds'],
      ),

      // Additional Dairy
      Ingredient(
        name: 'Cottage Cheese',
        category: 'Dairy',
        calories: 98,
        protein: 11,
        carbs: 3.4,
        fats: 4.3,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Dairy & Alternatives'],
      ),
      Ingredient(
        name: 'Almond Milk',
        category: 'Dairy',
        calories: 13,
        protein: 0.5,
        carbs: 0.3,
        fats: 1.1,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Dairy & Alternatives'],
      ),

      // More Proteins
      Ingredient(
        name: 'Tuna',
        category: 'Protein',
        calories: 132,
        protein: 28,
        carbs: 0,
        fats: 1.3,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Meat & Fish'],
      ),
      Ingredient(
        name: 'Black Beans',
        category: 'Protein',
        calories: 132,
        protein: 8.9,
        carbs: 23.7,
        fats: 0.5,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Plant-Based Protein'],
      ),
      Ingredient(
        name: 'Tempeh',
        category: 'Protein',
        calories: 192,
        protein: 20.3,
        carbs: 7.6,
        fats: 10.8,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Plant-Based Protein'],
      ),

      // More Vegetables
      Ingredient(
        name: 'Cauliflower',
        category: 'Vegetables',
        calories: 25,
        protein: 1.9,
        carbs: 5,
        fats: 0.3,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Vegetables & Greens'],
      ),
      Ingredient(
        name: 'Sweet Peas',
        category: 'Vegetables',
        calories: 81,
        protein: 5.4,
        carbs: 14,
        fats: 0.4,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Vegetables & Greens'],
      ),
      Ingredient(
        name: 'Asparagus',
        category: 'Vegetables',
        calories: 20,
        protein: 2.2,
        carbs: 3.9,
        fats: 0.2,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Vegetables & Greens'],
      ),

      // More Fruits
      const Ingredient(
        name: 'Strawberries',
        category: 'Fruits',
        calories: 32,
        protein: 0.7,
        carbs: 7.7,
        fats: 0.3,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Fruits'],
      ),
      const Ingredient(
        name: 'Mango',
        category: 'Fruits',
        calories: 60,
        protein: 0.8,
        carbs: 15,
        fats: 0.4,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Fruits'],
      ),

      // More Healthy Fats
      const Ingredient(
        name: 'Walnuts',
        category: 'Fats',
        calories: 654,
        protein: 15.2,
        carbs: 13.7,
        fats: 65.2,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Healthy Fats', 'Nuts & Seeds'],
      ),
      const Ingredient(
        name: 'Flax Seeds',
        category: 'Fats',
        calories: 534,
        protein: 18.3,
        carbs: 28.9,
        fats: 42.2,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Healthy Fats', 'Nuts & Seeds'],
      ),

      // More Dairy & Alternatives
      Ingredient(
        name: 'Soy Milk',
        category: 'Dairy',
        calories: 33,
        protein: 2.8,
        carbs: 3.2,
        fats: 1.7,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Dairy & Alternatives'],
      ),
      Ingredient(
        name: 'Mozzarella',
        category: 'Dairy',
        calories: 280,
        protein: 28,
        carbs: 3.1,
        fats: 17,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Dairy & Alternatives'],
      ),

      // More Carbs
      Ingredient(
        name: 'Buckwheat',
        category: 'Carbs',
        calories: 343,
        protein: 13.3,
        carbs: 71.5,
        fats: 3.4,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Carbs', 'Plant-Based Protein'],
      ),
      Ingredient(
        name: 'Couscous',
        category: 'Carbs',
        calories: 376,
        protein: 12.8,
        carbs: 77.4,
        fats: 0.6,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Carbs'],
      ),

      // Even More Proteins
      Ingredient(
        name: 'Cod Fish',
        category: 'Protein',
        calories: 82,
        protein: 17.8,
        carbs: 0,
        fats: 0.7,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Meat & Fish'],
      ),
      Ingredient(
        name: 'Chickpeas',
        category: 'Protein',
        calories: 164,
        protein: 8.9,
        carbs: 27,
        fats: 2.6,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Plant-Based Protein'],
      ),
      Ingredient(
        name: 'Pork Tenderloin',
        category: 'Protein',
        calories: 143,
        protein: 26,
        carbs: 0,
        fats: 3.5,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Meat & Fish'],
      ),

      // Even More Vegetables
      Ingredient(
        name: 'Zucchini',
        category: 'Vegetables',
        calories: 17,
        protein: 1.2,
        carbs: 3.1,
        fats: 0.3,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Vegetables & Greens'],
      ),
      Ingredient(
        name: 'Brussels Sprouts',
        category: 'Vegetables',
        calories: 43,
        protein: 3.4,
        carbs: 9,
        fats: 0.3,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Vegetables & Greens'],
      ),
      Ingredient(
        name: 'Carrots',
        category: 'Vegetables',
        calories: 41,
        protein: 0.9,
        carbs: 9.6,
        fats: 0.2,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Vegetables & Greens'],
      ),

      // Even More Fruits
      const Ingredient(
        name: 'Pineapple',
        category: 'Fruits',
        calories: 50,
        protein: 0.5,
        carbs: 13,
        fats: 0.1,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Fruits'],
      ),
      const Ingredient(
        name: 'Raspberries',
        category: 'Fruits',
        calories: 52,
        protein: 1.2,
        carbs: 11.9,
        fats: 0.7,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Fruits'],
      ),

      // Even More Healthy Fats
      const Ingredient(
        name: 'Pumpkin Seeds',
        category: 'Fats',
        calories: 559,
        protein: 30.2,
        carbs: 10.7,
        fats: 49.1,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Healthy Fats', 'Nuts & Seeds'],
      ),
      const Ingredient(
        name: 'Coconut Oil',
        category: 'Fats',
        calories: 862,
        protein: 0,
        carbs: 0,
        fats: 100,
        servingSize: '100',
        servingUnit: 'ml',
        specificCategories: ['Healthy Fats'],
      ),

      // Even More Dairy & Alternatives
      Ingredient(
        name: 'Oat Milk',
        category: 'Dairy',
        calories: 39,
        protein: 1.3,
        carbs: 7.2,
        fats: 1.5,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Dairy & Alternatives'],
      ),
      Ingredient(
        name: 'Feta Cheese',
        category: 'Dairy',
        calories: 264,
        protein: 14.2,
        carbs: 4.1,
        fats: 21.3,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Dairy & Alternatives'],
      ),

      // Even More Carbs
      Ingredient(
        name: 'Rye Bread',
        category: 'Carbs',
        calories: 259,
        protein: 8.5,
        carbs: 48.3,
        fats: 3.3,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Carbs'],
      ),
      Ingredient(
        name: 'Sorghum',
        category: 'Carbs',
        calories: 329,
        protein: 10.6,
        carbs: 72.1,
        fats: 3.3,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Carbs', 'Plant-Based Protein'],
      ),

      // More Protein Sources
      Ingredient(
        name: 'Venison',
        category: 'Protein',
        calories: 158,
        protein: 30.2,
        carbs: 0,
        fats: 3.2,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Meat & Fish'],
      ),
      Ingredient(
        name: 'Pinto Beans',
        category: 'Protein',
        calories: 143,
        protein: 9,
        carbs: 26,
        fats: 0.7,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Plant-Based Protein'],
      ),
      Ingredient(
        name: 'Octopus',
        category: 'Protein',
        calories: 82,
        protein: 14.9,
        carbs: 2,
        fats: 1.3,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Meat & Fish'],
      ),

      // More Vegetables
      Ingredient(
        name: 'Turnip',
        category: 'Vegetables',
        calories: 28,
        protein: 0.9,
        carbs: 6.4,
        fats: 0.1,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Vegetables & Greens'],
      ),
      Ingredient(
        name: 'Watercress',
        category: 'Vegetables',
        calories: 11,
        protein: 2.3,
        carbs: 1.3,
        fats: 0.1,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Vegetables & Greens'],
      ),
      Ingredient(
        name: 'Parsnips',
        category: 'Vegetables',
        calories: 75,
        protein: 1.2,
        carbs: 17.9,
        fats: 0.3,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Vegetables & Greens'],
      ),

      // More Fruits
      const Ingredient(
        name: 'Lychee',
        category: 'Fruits',
        calories: 66,
        protein: 0.8,
        carbs: 16.5,
        fats: 0.4,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Fruits'],
      ),
      const Ingredient(
        name: 'Guava',
        category: 'Fruits',
        calories: 68,
        protein: 2.6,
        carbs: 14.3,
        fats: 0.9,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Fruits'],
      ),

      // More Healthy Fats
      const Ingredient(
        name: 'Pine Nuts',
        category: 'Fats',
        calories: 673,
        protein: 13.7,
        carbs: 13.1,
        fats: 68.4,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Healthy Fats', 'Nuts & Seeds'],
      ),
      const Ingredient(
        name: 'Pistachio',
        category: 'Fats',
        calories: 562,
        protein: 20.2,
        carbs: 27.2,
        fats: 45.4,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Healthy Fats', 'Nuts & Seeds'],
      ),

      // More Dairy & Alternatives
      Ingredient(
        name: 'Hemp Milk',
        category: 'Dairy',
        calories: 46,
        protein: 2,
        carbs: 0.7,
        fats: 4.7,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Dairy & Alternatives'],
      ),
      Ingredient(
        name: 'Brie Cheese',
        category: 'Dairy',
        calories: 334,
        protein: 20.8,
        carbs: 0.5,
        fats: 27.7,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Dairy & Alternatives'],
      ),

      // More Carbs
      Ingredient(
        name: 'Teff',
        category: 'Carbs',
        calories: 367,
        protein: 13.3,
        carbs: 73.1,
        fats: 2.4,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Carbs', 'Plant-Based Protein'],
      ),
      Ingredient(
        name: 'Cassava',
        category: 'Carbs',
        calories: 159,
        protein: 1.4,
        carbs: 38,
        fats: 0.3,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Carbs'],
      ),
      Ingredient(
        name: 'Ground Beef',
        category: 'Protein',
        calories: 250,
        protein: 26,
        carbs: 0,
        fats: 15,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Meat & Fish'],
      ),
      Ingredient(
        name: 'Pasta',
        category: 'Carbs',
        calories: 158,
        protein: 5.8,
        carbs: 31,
        fats: 0.9,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Carbs'],
      ),
      
      Ingredient(
        name: 'Tomato',
        category: 'Vegetables',
        calories: 18,
        protein: 0.9,
        carbs: 3.9,
        fats: 0.2,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Vegetables & Greens'],
      ),
      Ingredient(
        name: 'Cucumber',
        category: 'Vegetables',
        calories: 15,
        protein: 0.6,
        carbs: 3.6,
        fats: 0.1,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Vegetables & Greens'],
      ),
      const Ingredient(
        name: 'Grapes',
        category: 'Fruits',
        calories: 69,
        protein: 0.7,
        carbs: 18,
        fats: 0.2,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Fruits'],
      ),
      const Ingredient(
        name: 'Pear',
        category: 'Fruits',
        calories: 57,
        protein: 0.4,
        carbs: 15,
        fats: 0.1,
        servingSize: '1',
        servingUnit: 'pc',
        specificCategories: ['Fruits'],
      ),
      Ingredient(
        name: 'Cheddar Cheese',
        category: 'Dairy',
        calories: 402,
        protein: 25,
        carbs: 1.3,
        fats: 33,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Dairy & Alternatives'],
      ),
      Ingredient(
        name: 'Red Potato',
        category: 'Carbs',
        calories: 89,
        protein: 2.3,
        carbs: 20.3,
        fats: 0.1,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Carbs'],
      ),
      Ingredient(
        name: 'Yukon Gold Potato',
        category: 'Carbs',
        calories: 89,
        protein: 2.3,
        carbs: 20.3,
        fats: 0.1,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Carbs'],
      ),
      Ingredient(
        name: 'Ground Turkey',
        category: 'Protein',
        calories: 170,
        protein: 22,
        carbs: 0,
        fats: 9,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Meat & Fish'],
      ),
      Ingredient(
        name: 'Lettuce',
        category: 'Vegetables',
        calories: 15,
        protein: 1.4,
        carbs: 2.9,
        fats: 0.2,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Vegetables & Greens'],
      ),
      Ingredient(
        name: 'Onion',
        category: 'Vegetables',
        calories: 40,
        protein: 1.1,
        carbs: 9.3,
        fats: 0.1,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Vegetables & Greens'],
      ),
      Ingredient(
        name: 'Garlic',
        category: 'Vegetables',
        calories: 149,
        protein: 6.4,
        carbs: 33,
        fats: 0.5,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Vegetables & Greens', 'Spices & Herbs'],
      ),
      const Ingredient(
        name: 'Peach',
        category: 'Fruits',
        calories: 39,
        protein: 0.9,
        carbs: 9.5,
        fats: 0.3,
        servingSize: '1',
        servingUnit: 'pc',
        specificCategories: ['Fruits'],
      ),
      const Ingredient(
        name: 'Watermelon',
        category: 'Fruits',
        calories: 30,
        protein: 0.6,
        carbs: 7.6,
        fats: 0.2,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Fruits'],
      ),
      Ingredient(
        name: 'Whole Milk',
        category: 'Dairy',
        calories: 61,
        protein: 3.2,
        carbs: 4.8,
        fats: 3.3,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Dairy & Alternatives'],
      ),
      Ingredient(
        name: 'White Rice',
        category: 'Carbs',
        calories: 130,
        protein: 2.7,
        carbs: 28,
        fats: 0.3,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Carbs'],
      ),

      // More Common Proteins
      Ingredient(
        name: 'Chicken Thighs',
        category: 'Protein',
        calories: 177,
        protein: 24,
        carbs: 0,
        fats: 8.5,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Meat & Fish'],
      ),
      Ingredient(
        name: 'Ground Pork',
        category: 'Protein',
        calories: 263,
        protein: 27,
        carbs: 0,
        fats: 17,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Meat & Fish'],
      ),
      Ingredient(
        name: 'Beef Steak',
        category: 'Protein',
        calories: 271,
        protein: 25.9,
        carbs: 0,
        fats: 17.9,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Meat & Fish'],
      ),

      // More Common Vegetables
      Ingredient(
        name: 'Green Onion',
        category: 'Vegetables',
        calories: 32,
        protein: 1.8,
        carbs: 7.3,
        fats: 0.2,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Vegetables & Greens'],
      ),
      Ingredient(
        name: 'Sweet Corn',
        category: 'Vegetables',
        calories: 86,
        protein: 3.2,
        carbs: 19,
        fats: 1.2,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Vegetables & Greens'],
      ),
      Ingredient(
        name: 'Cherry Tomatoes',
        category: 'Vegetables',
        calories: 27,
        protein: 1.3,
        carbs: 5.8,
        fats: 0.3,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Vegetables & Greens'],
      ),

      // More Common Fruits
      const Ingredient(
        name: 'Green Apple',
        category: 'Fruits',
        calories: 52,
        protein: 0.3,
        carbs: 13.8,
        fats: 0.2,
        servingSize: '1',
        servingUnit: 'pc',
        specificCategories: ['Fruits'],
      ),
      const Ingredient(
        name: 'Nectarine',
        category: 'Fruits',
        calories: 44,
        protein: 1.1,
        carbs: 10.6,
        fats: 0.3,
        servingSize: '1',
        servingUnit: 'pc',
        specificCategories: ['Fruits'],
      ),

      // More Common Dairy
      Ingredient(
        name: 'Low-fat Milk',
        category: 'Dairy',
        calories: 42,
        protein: 3.4,
        carbs: 5,
        fats: 1,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Dairy & Alternatives'],
      ),
      Ingredient(
        name: 'Plain Yogurt',
        category: 'Dairy',
        calories: 61,
        protein: 3.5,
        carbs: 4.7,
        fats: 3.3,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Dairy & Alternatives'],
      ),

      // More Common Carbs
      Ingredient(
        name: 'Bagel',
        category: 'Carbs',
        calories: 250,
        protein: 10,
        carbs: 48,
        fats: 1.5,
        servingSize: '1',
        servingUnit: 'pc',
        specificCategories: ['Carbs'],
      ),
      Ingredient(
        name: 'Tortilla',
        category: 'Carbs',
        calories: 237,
        protein: 6.1,
        carbs: 40.1,
        fats: 5.8,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Carbs'],
      ),

      // More Common Proteins
      Ingredient(
        name: 'Bacon',
        category: 'Protein',
        calories: 541,
        protein: 37,
        carbs: 1.4,
        fats: 42,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Meat & Fish'],
      ),
      Ingredient(
        name: 'Turkey Wings',
        category: 'Protein',
        calories: 221,
        protein: 23.1,
        carbs: 0,
        fats: 14.4,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Meat & Fish'],
      ),
      Ingredient(
        name: 'Beef Liver',
        category: 'Protein',
        calories: 135,
        protein: 20.4,
        carbs: 3.9,
        fats: 3.6,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Meat & Fish'],
      ),

      // More Common Vegetables
      Ingredient(
        name: 'Ginger',
        category: 'Vegetables',
        calories: 80,
        protein: 1.8,
        carbs: 17.8,
        fats: 0.8,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Vegetables & Greens', 'Spices & Herbs'],
      ),
      Ingredient(
        name: 'Red Onion',
        category: 'Vegetables',
        calories: 42,
        protein: 1.2,
        carbs: 9.9,
        fats: 0.1,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Vegetables & Greens'],
      ),
      Ingredient(
        name: 'Leeks',
        category: 'Vegetables',
        calories: 61,
        protein: 1.5,
        carbs: 14.2,
        fats: 0.3,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Vegetables & Greens'],
      ),

      // More Common Dairy
      Ingredient(
        name: 'Heavy Cream',
        category: 'Dairy',
        calories: 340,
        protein: 2.8,
        carbs: 2.7,
        fats: 36,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Dairy & Alternatives'],
      ),
      Ingredient(
        name: 'Butter',
        category: 'Dairy',
        calories: 717,
        protein: 0.9,
        carbs: 0.1,
        fats: 81,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Dairy & Alternatives'],
      ),

      // More Common Carbs
      Ingredient(
        name: 'Pita Bread',
        category: 'Carbs',
        calories: 275,
        protein: 9.1,
        carbs: 55.7,
        fats: 1.7,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Carbs'],
      ),

      // More Common Proteins
      Ingredient(
        name: 'Salmon Fillet',
        category: 'Protein',
        calories: 208,
        protein: 20,
        carbs: 0,
        fats: 13,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Meat & Fish', 'Healthy Fats'],
      ),
      Ingredient(
        name: 'Turkey Sausage',
        category: 'Protein',
        calories: 196,
        protein: 14,
        carbs: 1,
        fats: 16,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Meat & Fish'],
      ),
      Ingredient(
        name: 'Protein Powder',
        category: 'Protein',
        calories: 120,
        protein: 24,
        carbs: 3,
        fats: 1.5,
        servingSize: '30',
        servingUnit: 'g',
        specificCategories: ['Plant-Based Protein'],
      ),

      // More Common Vegetables
      Ingredient(
        name: 'Baby Spinach',
        category: 'Vegetables',
        calories: 23,
        protein: 2.9,
        carbs: 3.6,
        fats: 0.4,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Vegetables & Greens'],
      ),
      Ingredient(
        name: 'Romaine Lettuce',
        category: 'Vegetables',
        calories: 17,
        protein: 1.2,
        carbs: 3.3,
        fats: 0.3,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Vegetables & Greens'],
      ),

      // Common Breakfast Items
      const Ingredient(
        name: 'Granola',
        category: 'Carbs',
        calories: 471,
        protein: 10,
        carbs: 64,
        fats: 20,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Carbs', 'Healthy Fats'],
      ),
      const Ingredient(
        name: 'Honey',
        category: 'Carbs',
        calories: 304,
        protein: 0.3,
        carbs: 82,
        fats: 0,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Carbs', 'Condiments'],
      ),

      // Common Condiments
      const Ingredient(
        name: 'Peanut Butter',
        category: 'Fats',
        calories: 588,
        protein: 25,
        carbs: 20,
        fats: 50,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Healthy Fats', 'Plant-Based Protein', 'Condiments'],
      ),
      const Ingredient(
        name: 'Maple Syrup',
        category: 'Carbs',
        calories: 260,
        protein: 0,
        carbs: 67,
        fats: 0,
        servingSize: '100',
        servingUnit: 'ml',
        specificCategories: ['Carbs', 'Condiments'],
      ),

      // More Common Proteins
      Ingredient(
        name: 'Beef Mince',
        category: 'Protein',
        calories: 332,
        protein: 14.4,
        carbs: 0,
        fats: 30,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Meat & Fish'],
      ),
      Ingredient(
        name: 'Lamb Mince',
        category: 'Protein',
        calories: 282,
        protein: 16.6,
        carbs: 0,
        fats: 23.4,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Meat & Fish'],
      ),

      // More Common Vegetables
      Ingredient(
        name: 'Sweet Bell Pepper',
        category: 'Vegetables',
        calories: 31,
        protein: 1,
        carbs: 6,
        fats: 0.3,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Vegetables & Greens'],
      ),
      Ingredient(
        name: 'Mushroom',
        category: 'Vegetables',
        calories: 22,
        protein: 3.1,
        carbs: 3.3,
        fats: 0.3,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Vegetables & Greens'],
      ),

      // More Common Breakfast Items
      const Ingredient(
        name: 'Pancake',
        category: 'Carbs',
        calories: 227,
        protein: 6.4,
        carbs: 28.4,
        fats: 9.7,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Carbs'],
      ),
      const Ingredient(
        name: 'Waffle',
        category: 'Carbs',
        calories: 291,
        protein: 8,
        carbs: 34.2,
        fats: 14.1,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Carbs'],
      ),

      // More Common Snacks
      const Ingredient(
        name: 'Dark Chocolate',
        category: 'Carbs',
        calories: 546,
        protein: 7.8,
        carbs: 45.9,
        fats: 31.3,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Carbs', 'Healthy Fats'],
      ),
      const Ingredient(
        name: 'Trail Mix',
        category: 'Fats',
        calories: 462,
        protein: 15.3,
        carbs: 42.1,
        fats: 27.8,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Healthy Fats', 'Nuts & Seeds'],
      ),

      // More Common Condiments
      const Ingredient(
        name: 'Ketchup',
        category: 'Carbs',
        calories: 112,
        protein: 1.7,
        carbs: 26,
        fats: 0.2,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Carbs', 'Condiments'],
      ),
      const Ingredient(
        name: 'Mustard',
        category: 'Carbs',
        calories: 66,
        protein: 4.1,
        carbs: 6.4,
        fats: 3.9,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Carbs', 'Condiments'],
      ),

      // More Common Dairy Products
      Ingredient(
        name: 'Whey Protein',
        category: 'Protein',
        calories: 113,
        protein: 23.7,
        carbs: 2,
        fats: 0.5,
        servingSize: '30',
        servingUnit: 'g',
        specificCategories: ['Dairy & Alternatives'],
      ),
      Ingredient(
        name: 'Cottage Cheese Low Fat',
        category: 'Dairy',
        calories: 72,
        protein: 12.4,
        carbs: 2.7,
        fats: 1,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Dairy & Alternatives'],
      ),

      // More Spices & Herbs
      const Ingredient(
        name: 'Ground Ginger',
        category: 'Vegetables',
        calories: 335,
        protein: 8.9,
        carbs: 71.6,
        fats: 4.2,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Spices & Herbs'],
      ),
      const Ingredient(
        name: 'Nutmeg',
        category: 'Vegetables',
        calories: 525,
        protein: 5.8,
        carbs: 49.3,
        fats: 36.3,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Spices & Herbs'],
      ),
      Ingredient(
        name: 'Parsley',
        category: 'Vegetables',
        calories: 36,
        protein: 3,
        carbs: 6.3,
        fats: 0.8,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Vegetables & Greens', 'Spices & Herbs'],
      ),
      Ingredient(
        name: 'Dill',
        category: 'Vegetables',
        calories: 43,
        protein: 3.5,
        carbs: 7,
        fats: 1.1,
        servingSize: weightUnit == 'kg' ? '100' : '4',
        servingUnit: weightUnit == 'kg' ? 'g' : 'oz',
        specificCategories: ['Vegetables & Greens', 'Spices & Herbs'],
      ),
      const Ingredient(
        name: 'Curry Powder',
        category: 'Vegetables',
        calories: 325,
        protein: 14.3,
        carbs: 58.4,
        fats: 14,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Spices & Herbs'],
      ),
      const Ingredient(
        name: 'Italian Seasoning',
        category: 'Vegetables',
        calories: 272,
        protein: 9.6,
        carbs: 64.1,
        fats: 7.4,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Spices & Herbs'],
      ),

      // More Condiments
      const Ingredient(
        name: 'BBQ Sauce',
        category: 'Carbs',
        calories: 172,
        protein: 1.2,
        carbs: 42.4,
        fats: 0.5,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Carbs', 'Condiments'],
      ),
      const Ingredient(
        name: 'Soy Sauce',
        category: 'Carbs',
        calories: 53,
        protein: 8.1,
        carbs: 4.9,
        fats: 0.6,
        servingSize: '100',
        servingUnit: 'ml',
        specificCategories: ['Condiments'],
      ),
      const Ingredient(
        name: 'Hot Sauce',
        category: 'Vegetables',
        calories: 11,
        protein: 0.7,
        carbs: 2.5,
        fats: 0.1,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Condiments', 'Spices & Herbs'],
      ),
      const Ingredient(
        name: 'Ranch Dressing',
        category: 'Fats',
        calories: 444,
        protein: 2.6,
        carbs: 10.3,
        fats: 45.1,
        servingSize: '100',
        servingUnit: 'g',
        specificCategories: ['Condiments', 'Healthy Fats'],
      ),
      const Ingredient(
        name: 'Balsamic Vinegar',
        category: 'Carbs',
        calories: 88,
        protein: 0.5,
        carbs: 17.3,
        fats: 0,
        servingSize: '100',
        servingUnit: 'ml',
        specificCategories: ['Condiments'],
      ),
      const Ingredient(
        name: 'Teriyaki Sauce',
        category: 'Carbs',
        calories: 89,
        protein: 5.5,
        carbs: 16.5,
        fats: 0.1,
        servingSize: '100',
        servingUnit: 'ml',
        specificCategories: ['Condiments'],
      ),
    ];
  }

  static List<Ingredient> getIngredientsByCategory(BuildContext context, String category) {
    return getIngredients(context)
        .where((ingredient) => ingredient.category == category)
        .toList();
  }

  static List<Ingredient> searchIngredients(BuildContext context, String query) {
    return getIngredients(context)
        .where((ingredient) => ingredient.name.toLowerCase().contains(query.toLowerCase()))
            .toList();
  }

  // Add this method to filter ingredients by specific category
  static List<Ingredient> getIngredientsBySpecificCategory(BuildContext context, String specificCategory) {
    if (specificCategory == 'All') {
      return getIngredients(context);
    }
    return getIngredients(context)
        .where((ingredient) => ingredient.specificCategories.contains(specificCategory))
        .toList();
  }

  static List<Ingredient> getPaginatedIngredients(BuildContext context, String query, int page, int pageSize) {
    final allIngredients = getIngredients(context);
    final filteredIngredients = query.isEmpty
        ? allIngredients
        : allIngredients
            .where((ingredient) =>
                ingredient.name.toLowerCase().contains(query.toLowerCase()))
            .toList();

    final startIndex = page * pageSize;
    if (startIndex >= filteredIngredients.length) {
      return [];
    }

    final endIndex = (startIndex + pageSize) > filteredIngredients.length
        ? filteredIngredients.length
        : startIndex + pageSize;

    return filteredIngredients.sublist(startIndex, endIndex);
  }
} 